apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: user-service
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    app: kafka