apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: user-service
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
  selector:
    app: zookeeper